# Generated by Django 4.0.4 on 2022-10-10 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('has_basket', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('P', 'pending'), ('R', 'ready')], default='pending', max_length=1)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.bike')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.frame'),
        ),
        migrations.AddField(
            model_name='bike',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.seat'),
        ),
        migrations.AddField(
            model_name='bike',
            name='tire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.tire'),
        ),
    ]
